// <auto-generated />
using System;
using Frogling.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frogling.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922141913_ChangeUserProfile")]
    partial class ChangeUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Frogling.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduleItemId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Frogling.Api.Models.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeCategory")
                        .HasColumnType("int");

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("int");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("ScheduleItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeCategory = 3,
                            AvailableSlots = 3,
                            DayOfWeek = "Понедельник",
                            GroupName = "Малыши (1-3 года)",
                            Time = "15:00 - 15:45",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgeCategory = 3,
                            AvailableSlots = 2,
                            DayOfWeek = "Понедельник",
                            GroupName = "Головастики (4-6 лет)",
                            Time = "16:00 - 16:45",
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 3,
                            AgeCategory = 3,
                            AvailableSlots = 4,
                            DayOfWeek = "Среда",
                            GroupName = "Малыши (1-3 года)",
                            Time = "15:00 - 15:45",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 4,
                            AgeCategory = 3,
                            AvailableSlots = 1,
                            DayOfWeek = "Среда",
                            GroupName = "Пловцы (7-10 лет)",
                            Time = "17:00 - 17:45",
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 5,
                            AgeCategory = 3,
                            AvailableSlots = 5,
                            DayOfWeek = "Пятница",
                            GroupName = "Головастики (4-6 лет)",
                            Time = "16:00 - 16:45",
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("Frogling.Api.Models.ServicePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorTheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServicePlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Разовые",
                            ColorTheme = "emerald",
                            Description = "Знакомство с тренером и водой для малышей от 2 месяцев.",
                            DurationDays = 7,
                            IsActive = true,
                            LessonsCount = 1,
                            Price = 0m,
                            Title = "Пробное занятие"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Абонементы",
                            ColorTheme = "emerald",
                            Description = "Идеально для начинающих. 4 занятия, которые можете посетить в любые дни месяца по записи",
                            DurationDays = 30,
                            IsActive = true,
                            LessonsCount = 4,
                            Price = 6000m,
                            Title = "Юный пловец"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Абонементы",
                            ColorTheme = "blue",
                            Description = "Занятия родителя, тренера и ребенка. 4 занятия в месяц",
                            DurationDays = 45,
                            IsActive = true,
                            LessonsCount = 4,
                            Price = 7400m,
                            Title = "Семейный абонемент"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Разовое",
                            ColorTheme = "amber",
                            Description = "Разовое занятие групповое",
                            DurationDays = 30,
                            IsActive = true,
                            LessonsCount = 1,
                            Price = 1100m,
                            Title = "Групповое посещение"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Персональные",
                            ColorTheme = "blue",
                            Description = "Персональное 45-минутное занятие один на один с инструктором.",
                            DurationDays = 14,
                            IsActive = true,
                            LessonsCount = 1,
                            Price = 1600m,
                            Title = "Индивидуальное с тренером"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Разовые",
                            ColorTheme = "emerald",
                            Description = "Персональное занятие 60 минут",
                            DurationDays = 30,
                            IsActive = true,
                            LessonsCount = 1,
                            Price = 1600m,
                            Title = "Разовые посещение"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Абонементы",
                            ColorTheme = "emerald",
                            Description = "Идеально для начинающих. 8 занятий, которые можете посетить в любые дни месяца по записи",
                            DurationDays = 30,
                            IsActive = true,
                            LessonsCount = 8,
                            Price = 11500m,
                            Title = "Активный пловец"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Абонементы",
                            ColorTheme = "blue",
                            Description = "Занятия родителя, тренера и ребенка. 8 занятия в месяц",
                            DurationDays = 45,
                            IsActive = true,
                            LessonsCount = 8,
                            Price = 14000m,
                            Title = "Семейный Плюс"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Разовое",
                            ColorTheme = "amber",
                            Description = "Абонемент за 4 групповых занятия",
                            DurationDays = 30,
                            IsActive = true,
                            LessonsCount = 4,
                            Price = 4100m,
                            Title = "Групповой абонемент"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Разовое",
                            ColorTheme = "amber",
                            Description = "Абонемент за 8 групповых занятия",
                            DurationDays = 30,
                            IsActive = true,
                            LessonsCount = 8,
                            Price = 8000m,
                            Title = "Групповой абонемент"
                        });
                });

            modelBuilder.Entity("Frogling.Api.Models.SubscriptionPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RemainingLessons")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Frogling.Api.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Certificates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportsСareer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportsСategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Certificates = "Специалист грудничкового и малышкового плавания. Специалист спортивного и детского массажа",
                            Education = "ПГУФКСиТ, специализация тренер по плаванию",
                            Experience = "3 года",
                            Name = "Любовь",
                            PhotoUrl = "👩‍🏫",
                            Specialization = "Специалист по грудничковому плаванию",
                            SportsСareer = "12 лет спортивной карьеры",
                            SportsСategory = "Мастер спорта по плаванию"
                        },
                        new
                        {
                            Id = 2,
                            Certificates = "Специалист грудничкового и малышкового плавания",
                            Education = "ПГУФКСиТ, специализация тренер по плаванию",
                            Experience = " 3 года",
                            Name = "Владислав",
                            PhotoUrl = "👨‍🏫",
                            Specialization = "Раннее обучение плаванию",
                            SportsСareer = "12 лет спортивной карьеры, участник всероссийских соревнований",
                            SportsСategory = "Кандидат мастера спорта по плаванию"
                        },
                        new
                        {
                            Id = 3,
                            Certificates = "Специалист грудничкового и малышкового плавания. Детский массажист/Преподаватель детского массажа и моторного развития",
                            Education = "КГМУ Сестринское дело",
                            Experience = "2 года",
                            Name = "Лидия",
                            PhotoUrl = "🏊‍♀️",
                            Specialization = "Аквааэробика и ЛФК",
                            SportsСareer = "Специалист физической терапии детей и взрослых",
                            SportsСategory = ""
                        });
                });

            modelBuilder.Entity("Frogling.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMedicalExaminationValid")
                        .HasColumnType("bit");

                    b.Property<string>("ParentsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Frogling.Api.Models.Booking", b =>
                {
                    b.HasOne("Frogling.Api.Models.ScheduleItem", "ScheduleItem")
                        .WithMany()
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frogling.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frogling.Api.Models.ScheduleItem", b =>
                {
                    b.HasOne("Frogling.Api.Models.Trainer", "Trainer")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Frogling.Api.Models.SubscriptionPrice", b =>
                {
                    b.HasOne("Frogling.Api.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frogling.Api.Models.Trainer", b =>
                {
                    b.Navigation("ScheduleItems");
                });

            modelBuilder.Entity("Frogling.Api.Models.User", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
