// <auto-generated />
using System;
using Frogling.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frogling.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Frogling.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduleItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleItemId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleItemId");

                    b.HasIndex("ScheduleItemId1");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Frogling.Api.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Frogling.Api.Models.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("ScheduleItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSlots = 6,
                            DurationMinutes = 45,
                            GroupName = "Грудничковое плавание",
                            StartAt = new DateTime(2026, 10, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailableSlots = 5,
                            DurationMinutes = 45,
                            GroupName = "Малыши 1–3 года",
                            StartAt = new DateTime(2026, 10, 6, 16, 30, 0, 0, DateTimeKind.Utc),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 3,
                            AvailableSlots = 6,
                            DurationMinutes = 45,
                            GroupName = "Головастики 4–6 лет",
                            StartAt = new DateTime(2026, 10, 7, 15, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 4,
                            AvailableSlots = 4,
                            DurationMinutes = 45,
                            GroupName = "Пловцы 7–10 лет",
                            StartAt = new DateTime(2026, 10, 8, 17, 15, 0, 0, DateTimeKind.Utc),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 5,
                            AvailableSlots = 5,
                            DurationMinutes = 45,
                            GroupName = "Интенсив",
                            StartAt = new DateTime(2026, 10, 9, 16, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 6,
                            AvailableSlots = 8,
                            DurationMinutes = 45,
                            GroupName = "Семейное плавание",
                            StartAt = new DateTime(2026, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 7,
                            AvailableSlots = 10,
                            DurationMinutes = 45,
                            GroupName = "Свободное плавание",
                            StartAt = new DateTime(2026, 10, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 3
                        });
                });

            modelBuilder.Entity("Frogling.Api.Models.ServicePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorTheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("bit");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServicePlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Разовые",
                            ColorTheme = "emerald",
                            Description = "Знакомство с тренером и водой для малышей от 2 месяцев.",
                            DurationDays = 7,
                            IsActive = true,
                            IsTrial = false,
                            LessonsCount = 1,
                            Price = 0m,
                            Title = "Пробное занятие"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Абонементы",
                            ColorTheme = "emerald",
                            Description = "Идеально для начинающих. 4 занятия, которые можете посетить в любые дни месяца по записи",
                            DurationDays = 30,
                            IsActive = true,
                            IsTrial = false,
                            LessonsCount = 4,
                            Price = 6000m,
                            Title = "Юный пловец"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Абонементы",
                            ColorTheme = "blue",
                            Description = "Занятия родителя, тренера и ребенка. 4 занятия в месяц",
                            DurationDays = 45,
                            IsActive = true,
                            IsTrial = false,
                            LessonsCount = 4,
                            Price = 7400m,
                            Title = "Семейный абонемент"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Разовое",
                            ColorTheme = "amber",
                            Description = "Разовое занятие групповое",
                            DurationDays = 30,
                            IsActive = true,
                            IsTrial = false,
                            LessonsCount = 1,
                            Price = 1100m,
                            Title = "Групповое посещение"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Персональные",
                            ColorTheme = "blue",
                            Description = "Персональное 45-минутное занятие один на один с инструктором.",
                            DurationDays = 14,
                            IsActive = true,
                            IsTrial = false,
                            LessonsCount = 1,
                            Price = 1600m,
                            Title = "Индивидуальное с тренером"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Разовые",
                            ColorTheme = "emerald",
                            Description = "Персональное занятие 60 минут",
                            DurationDays = 30,
                            IsActive = true,
                            IsTrial = false,
                            LessonsCount = 1,
                            Price = 1600m,
                            Title = "Разовые посещение"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Абонементы",
                            ColorTheme = "emerald",
                            Description = "Идеально для начинающих. 8 занятий, которые можете посетить в любые дни месяца по записи",
                            DurationDays = 30,
                            IsActive = true,
                            IsTrial = false,
                            LessonsCount = 8,
                            Price = 11500m,
                            Title = "Активный пловец"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Абонементы",
                            ColorTheme = "blue",
                            Description = "Занятия родителя, тренера и ребенка. 8 занятия в месяц",
                            DurationDays = 45,
                            IsActive = true,
                            IsTrial = false,
                            LessonsCount = 8,
                            Price = 14000m,
                            Title = "Семейный Плюс"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Разовое",
                            ColorTheme = "amber",
                            Description = "Абонемент за 4 групповых занятия",
                            DurationDays = 30,
                            IsActive = true,
                            IsTrial = false,
                            LessonsCount = 4,
                            Price = 4100m,
                            Title = "Групповой абонемент"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Разовое",
                            ColorTheme = "amber",
                            Description = "Абонемент за 8 групповых занятия",
                            DurationDays = 30,
                            IsActive = true,
                            IsTrial = false,
                            LessonsCount = 8,
                            Price = 8000m,
                            Title = "Групповой абонемент"
                        });
                });

            modelBuilder.Entity("Frogling.Api.Models.SubscriptionPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RemainingLessons")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Frogling.Api.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Certificates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportsСareer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportsСategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Certificates = "Специалист грудничкового и малышкового плавания.",
                            Education = "ПГУФКСиТ, специализация тренер по плаванию",
                            Experience = "3 года",
                            Name = "Любовь",
                            PhotoUrl = "👩‍🏫",
                            Specialization = "Специалист по грудничковому плаванию",
                            SportsСareer = "12 лет спортивной карьеры",
                            SportsСategory = "Мастер спорта по плаванию",
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = 2,
                            Certificates = "Специалист грудничкового и малышкового плавания",
                            Education = "ПГУФКСиТ, специализация тренер по плаванию",
                            Experience = "3 года",
                            Name = "Владислав",
                            PhotoUrl = "👨‍🏫",
                            Specialization = "Раннее обучение плаванию",
                            SportsСareer = "12 лет спортивной карьеры",
                            SportsСategory = "Кандидат мастера спорта по плаванию",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = 3,
                            Certificates = "Специалист грудничкового и малышкового плавания.",
                            Education = "КГМУ Сестринское дело",
                            Experience = "2 года",
                            Name = "Лидия",
                            PhotoUrl = "🏊‍♀️",
                            Specialization = "Аквааэробика и ЛФК",
                            SportsСareer = "Специалист физической терапии детей и взрослых",
                            SportsСategory = "",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("Frogling.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MedicalCheckDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 25, 8, 23, 41, 481, DateTimeKind.Utc).AddTicks(3393),
                            Email = "admin@frogling.ru",
                            FullName = "Главный Администратор",
                            MedicalCheckDate = new DateTime(2026, 9, 25, 8, 23, 41, 481, DateTimeKind.Utc).AddTicks(3431),
                            ParentName = "",
                            PasswordHash = "$2a$11$z4Ygli8Z.polnSU12EiJMeYSqB4woIbWm02mdnyPxRIKErPPkAq52",
                            Phone = "",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 9, 25, 8, 23, 41, 481, DateTimeKind.Utc).AddTicks(3438),
                            Email = "luba@frogling.ru",
                            FullName = "Любовь (Тренер)",
                            MedicalCheckDate = new DateTime(2026, 9, 25, 8, 23, 41, 481, DateTimeKind.Utc).AddTicks(3438),
                            ParentName = "",
                            PasswordHash = "$2a$11$jPu9PCjT/qHI0GGIMc.rKORjqOzOYBv/Na/Q7yYMwF/8jBQQA5ZUe",
                            Phone = "",
                            Role = "Trainer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 9, 25, 8, 23, 41, 481, DateTimeKind.Utc).AddTicks(3442),
                            Email = "vlad@frogling.ru",
                            FullName = "Владислав (Тренер)",
                            MedicalCheckDate = new DateTime(2026, 9, 25, 8, 23, 41, 481, DateTimeKind.Utc).AddTicks(3441),
                            ParentName = "",
                            PasswordHash = "$2a$11$jPu9PCjT/qHI0GGIMc.rKORjqOzOYBv/Na/Q7yYMwF/8jBQQA5ZUe",
                            Phone = "",
                            Role = "Trainer"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 9, 25, 8, 23, 41, 481, DateTimeKind.Utc).AddTicks(3444),
                            Email = "lida@frogling.ru",
                            FullName = "Лидия (Тренер)",
                            MedicalCheckDate = new DateTime(2026, 9, 25, 8, 23, 41, 481, DateTimeKind.Utc).AddTicks(3444),
                            ParentName = "",
                            PasswordHash = "$2a$11$jPu9PCjT/qHI0GGIMc.rKORjqOzOYBv/Na/Q7yYMwF/8jBQQA5ZUe",
                            Phone = "",
                            Role = "Trainer"
                        });
                });

            modelBuilder.Entity("Frogling.Api.Models.Booking", b =>
                {
                    b.HasOne("Frogling.Api.Models.ScheduleItem", "ScheduleItem")
                        .WithMany()
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frogling.Api.Models.ScheduleItem", null)
                        .WithMany("Bookings")
                        .HasForeignKey("ScheduleItemId1");

                    b.HasOne("Frogling.Api.Models.SubscriptionPrice", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frogling.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleItem");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frogling.Api.Models.ScheduleItem", b =>
                {
                    b.HasOne("Frogling.Api.Models.Trainer", "Trainer")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Frogling.Api.Models.SubscriptionPrice", b =>
                {
                    b.HasOne("Frogling.Api.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frogling.Api.Models.Trainer", b =>
                {
                    b.HasOne("Frogling.Api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Frogling.Api.Models.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frogling.Api.Models.ScheduleItem", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Frogling.Api.Models.Trainer", b =>
                {
                    b.Navigation("ScheduleItems");
                });

            modelBuilder.Entity("Frogling.Api.Models.User", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
